name: Auth Service CI/CD

on:
  push:
    paths:
      - 'services/auth-service/**'
      - '.github/workflows/auth-service-ci.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ./services/auth-serice
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/auth-service:latest
          ghcr.io/${{ github.repository }}/auth-service:${{ github.sha }}
